#pragma kernel CSMain

#define CHUNK_SIZE 32

RWTexture3D<float> densityField;

[numthreads(8, 8, 8)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= CHUNK_SIZE || id.y >= CHUNK_SIZE || id.z >= CHUNK_SIZE)
        return;

    float3 position = float3(id.x, id.y, id.z);
    float density = sin(position.x * 0.1f) * cos(position.y * 0.1f) * sin(position.z * 0.1f);

    densityField[id] = density;
}
